# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ee3465968d4a9f7ac74048776707c51bd6bdca111e586f2776919d8ecdf1c25674cb2d708120194f47578a493c948c4a57679132b63d37ed01a4f7137a0ae1a

test:
  secret_key_base: 84089f707c66a6ea71c6e8a531e7e9862f11ba73858432e1770a0a0c9a90cc5fc266e7c8b83e5854068d711b229bb04df1f64357a422c245851e2a722cd3db6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
